### PR TITLE
Add option to clear Nuget cache

### PR DESCRIPTION
**Pull request by degrim**
Add a `CLEAR_NUGET_CACHE` environment variable to allow clearing the NuGet packages cache.

### CODE REVIEW

**Comment by opiethehokie** [comment]
I'm wondering if this should be more like the node.js buildpack and provide an env var to not use the cache (NODE_MODULES_CACHE=false), and also not restore the cache when something changes that would invalidate it (like node or npm version changing)? 

Then I guess the only way to clear the cache is to create a new app, but I think it's at least worth thinking about whether it would work for this buildpack. 

It does seem slightly different since changing the package source could affect the validity of the cache, but maybe a changed nuget.config could be the signal to not restore the cache? We could probably just store a hash of the file to check if it changed.

**Comment by degrim** [comment]
- Changed the environment variable to CACHE_NUGET_PACKAGES
- Setting CACHE_NUGET_PACKAGES=false will clear any existing packages in the NuGet packages cache, and will not save any new packages to the cache
- NuGet packages cache will also be cleared when the .NET CLI version changes as this generally causes issues with cached packages when upgrading to a new .NET CLI version.

**Comment by flavorjones** [comment]
This feels like something we might want to implement across all the buildpacks in a generic way (rather than a specific way just for this buildpack and just for nuget).

For example, it might be a reasonable thing to want to blow away the application cache for a ruby/bundler app as well.

On the other hand, I'd expect nuget to handle all this properly if I change my dependencies ... Help me understand why this feature's necessary in that case? Caveat: I don't know much about nuget.

**Comment by degrim** [comment]
@flavorjones A problem occurs when you use a pre-release NuGet feed and pull in packages from RC3 for example, when RC2 is the latest stable version.  If those RC3 packages pulled in higher versions of dependent packages and you then reverted back to using the stable NuGet feed which gave you RC2 packages, your RC2 packages might pull in those cached RC3 packages due to wildcards in their dependencies rather than going to the stable NuGet feed to get the latest dependency which exists on that feed.  NuGet will always take the local copy which matches before attempting to download from the currently configured feed.

**Comment by flavorjones** [comment]
Ah, OK - thanks for explaining, that makes sense.

@sclevine WDYT about making app-cache-busting a more general thing?

**Comment by sclevine** [comment]
Don't let me hold up this PR, I think it's fine. We have a story to discuss a longer-term strategy here: https://www.pivotaltracker.com/story/show/132038259

**Pull request closed without merging**
